version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ftn
      POSTGRES_DB: uns
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ftn:
    image: ggmaz/cloud-project:ftn
    environment:
      NAME: ftn
    ports:
      - "8060:8060"

  pmf:
    image: ggmaz/cloud-project:ftn
    environment:
      NAME: pmf
    ports:
      - "8070:8060"

  pravni:
    image: ggmaz/cloud-project:ftn
    environment:
      NAME: pravni
    ports:
      - "8090:8060"

  uns1:
    image: ggmaz/cloud-project:uns
    restart: always
    ports:
      - "8051:8050"
    depends_on:
      db:
        condition: service_healthy

  uns2:
    image: ggmaz/cloud-project:uns
    restart: always
    ports:
      - "8052:8050"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - uns1
      - uns2
    ports:
      - "80:80"
